### ISSUE TITLE
Outdated city names after the last renaming

### ISSUE THREAD

**Issue by nazbez** [Tyrrrz/SpellingUkraine#33]
### Details

Hello!

I noticed that some cities in the dictionary have outdated names after [the last update by the Ukrainian government](https://zakon.rada.gov.ua/laws/show/3984-IX#Text). 

For example:
- ~~Pershotravensk~~ Shakhtarske;
- ~~Sievierodonetsk~~ Siverskodonetsk;
- ~~Pervomaiskyi~~ Zlatopil.

I would make a pull request, but I don't know if I should just rename the old city names or add the new ones and keep the old ones.

### Checklist

- [X] I have looked through existing issues to make sure that this feature has not been requested before
- [X] I have provided a descriptive title for this issue
- [X] I am aware that even valid feature requests may be rejected if they do not align with the project's goals
- [x] I have sponsored this project

**Comment by Tyrrrz** [comment]
Hi! Thank you for letting me know. Please feel free to create a PR to update the relevant records: https://github.com/Tyrrrz/SpellingUkraine/tree/master/data/vocabulary/places
