### ISSUE TITLE
Add Lwiw as the German transliteration for Львів

### ISSUE THREAD

**Issue by nils-a** [Tyrrrz/SpellingUkraine#4]
### Details

In Germany, the international (English) transliterated `v` is transliterated as `w` (I'm guessing it's the `в` that's being transliterated here).

So, it seems Lwiw is a "good" name for Lviv. See https://de.wikipedia.org/wiki/Lwiw

**Comment by nils-a** [comment]
I added `Lwiw` as an alias in https://github.com/nils-a/SpellingUkraine/commit/2cc724981d71f2c8e95b665b812e601897aa490d - happy to submit a PR, if you feel "aliases" is the correct place.

**Comment by Tyrrrz** [comment]
Yes, please submit a PR. Aliases is currently the best place for this, although I'm beginning to see that there are limitations with this structure. But for now, let's add it there.
