### ISSUE TITLE
Zelenskyy vs Zelenskyi

### ISSUE THREAD

**Issue by oleksiilevzhynskyi** [Tyrrrz/SpellingUkraine#5]
### Details

Hey. According to the official rules for [transliteration](https://pasport.org.ua/faq/transliteration), **Зеленський** should be **Zelenskyi**. Is there any proof why "yy" is used instead of "yi"?

Example from online converter - http://translit.kh.ua/

<img width="809" alt="Screenshot 2022-03-17 at 13 31 45" src="https://user-images.githubusercontent.com/576013/158800107-3424c650-caec-4bbf-978b-6667f0b5d07e.png">

**Comment by oleksiilevzhynskyi** [comment]
The line in code - https://github.com/Tyrrrz/SpellingUkraine/blob/master/data/vocabulary/people/volodymyr_zelenskyy.json#L4

**Comment by oleksiilevzhynskyi** [comment]
Got it! Thanks for the detailed explanation. Closed.

**Comment by Tyrrrz** [comment]
By the way, you can now use this page to transliterate any text according to the current rules (the ones you linked on pasport.org.ua):

https://spellingukraine.com/translit

**Comment by Golova1111** [comment]
I would add that Zelensk(y|i)y itself used incorrect transliteration on Telegram (gov site and twitter used correct spelling)
![image](https://user-images.githubusercontent.com/28533365/160216355-d29ee470-9b27-4104-a9da-90ec8bfd99ef.png)

**Comment by Tyrrrz** [comment]
😅 

![image](https://user-images.githubusercontent.com/1935960/160216800-0f483256-470f-4313-8fd2-c466a01bb4e7.png)
